### PR TITLE
Added the set_chunk_size handler call in the dealer...

### PR DESCRIPTION
**Pull request by Scylardor**
... to allow drivers to force a specific chunk size (restricted by some services).

### CODE REVIEW

**Comment by k4nar** [comment]
Can you add it to the doc as well ? The handlers are described in `docs/drivers.rst`.

**Comment by Scylardor** [comment]
That should be it. Is it okay ?

**Comment by k4nar** [comment]
Needs a rebase (there's a conflict I think).

**Comment by Scylardor** [comment]
That should be good now.

**Pull request merged**
